### ISSUE TITLE
No Color Setting ,No Sizes Setting

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/SmartShoppingCart#7]
No Color Setting ,No Sizes Setting

**Comment by WaqarShah** [comment]
Steps for Color and Size Settings : 

1. Login with Admin.
2. Click on Catalogue drop down menu -> click on categories -> click on any category title in Actions side
then click on purple symbol for add colors -> Now add category color and category color code and submit etc. Red, #ccc. 
Same above procedure is for adjusting sizes of categories. after adding color and sizes these colors and sizes are shown on that product on  products detail page of that category product.
